# Menus
bindd = SUPER, SPACE, Launch apps, exec, sublingual-os-launch-walker
bindd = SUPER CTRL, E, Emoji picker, exec, sublingual-os-launch-walker -m symbols
bindd = SUPER CTRL, C, Capture menu, exec, sublingual-os-menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, sublingual-os-menu toggle
bindd = SUPER ALT, SPACE, Sublingual OS menu, exec, sublingual-os-menu
bindd = SUPER SHIFT, code:201, Sublingual OS menu, exec, sublingual-os-menu
bindd = SUPER, ESCAPE, System menu, exec, sublingual-os-menu system
bindld = , XF86PowerOff, Power menu, exec, sublingual-os-menu system
bindd = SUPER, K, Show key bindings, exec, sublingual-os-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, sublingual-os-toggle-waybar
bindd = SUPER CTRL, SPACE, Theme background menu, exec, sublingual-os-menu background
bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, sublingual-os-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, sublingual-os-hyprland-active-window-transparency-toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, sublingual-os-hyprland-window-gaps-toggle
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, sublingual-os-hyprland-window-single-square-aspect-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, sublingual-os-toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, sublingual-os-toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, sublingual-os-toggle-nightlight
bindd = SUPER CTRL, Delete, Toggle laptop display, exec, sublingual-os-hyprland-monitor-internal-toggle

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec, sublingual-os-brightness-display-apple -5000
bindd = CTRL, F2, Apple Display brightness up, exec, sublingual-os-brightness-display-apple +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec, sublingual-os-brightness-display-apple +60000

# Captures
bindd = , PRINT, Screenshot, exec, sublingual-os-cmd-screenshot
bindd = ALT, PRINT, Screenrecording, exec, sublingual-os-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# File sharing
bindd = SUPER CTRL, S, Share, exec, sublingual-os-menu share

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "    $(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send -u low "$(sublingual-os-battery-status)"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, sublingual-os-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, sublingual-os-launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, sublingual-os-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, sublingual-os-launch-tui btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, sublingual-os-lock-screen
